interval: 5
fog:
  radius: 15
  density: 18888
  duration: 600
  worlds:
    - test
    - world
acid_rain:
  duration: 600
  worlds:
    - test
    - world
meteor_shower:
  chance: 80
  worlds:
    - test
  min_height: 70
  length: 8

