##################################
#                                #
#                                #
#          XiWeather             #
#                                #
#                                #
##################################

#天气刷新间隔，单位秒
interval: 3

#雾霾天气
fog:
  #影响范围（以玩家为中心）
  radius: 15
  #雾霾密度
  density: 8000
  #影响时长（s）
  duration: 60
  #影响世界
  worlds:
    - test
    - world

#酸雨
acid_rain:
  duration: 60
  worlds:
    - test
    - world

#大风
wind:
  duration: 60
  worlds:
    - test
    - world
  radius: 9
  #粒子密度
  particle_count: 280
  #强度 粒子密度和强度挂钩，强度越高速度越快，密度越高速度越慢
  strength: 15.0
  #粒子效果长度
  distance: 16.0
  #玩家获得的速度加成等级
  player_speed: 1
#雷暴
thunderstorm:
  duration: 60
  worlds:
    - test
    - world
  chance: 0.3 #每秒被雷击的概率
  radius: 16 #打击半径
  delay: 20

#流星雨
meteor_shower:
  chance: 80
  worlds:
    - test
  min_height: 70
  length: 8

